name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to VM
        run: |
          gcloud compute ssh "instance-20240531-184519" \
          --project ${{ secrets.GCP_PROJECT }} \
          --zone "us-central1-a" \
          --command "
            cd  Nx-task &&
            git pull &&
            npm run build
            pm2 restart all
          "
