name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          install_components: gcloud

      - name: Deploy to VM
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud compute ssh "instance-20240531-184519" \
          --zone "us-central1-a" \
          --command "
            cd  Nx-task &&
            git pull &&
            npm run build
            pm2 restart all
          "
